jail, fixed errors not showing, highlight lines

diff --git a/latexwrapper b/latexwrapper
--- a/latexwrapper
+++ b/latexwrapper
@@ -6,7 +6,10 @@ YELLOW='\033[1;33m'
 GREEN='\033[1;32m'
 RESET='\033[0m'
 
+SELF=$(realpath "$0")
+
 f=
+fz=
 f_bib=
 cmd=build
 compiler=pdflatex
@@ -18,8 +21,7 @@ run_showing() {
 }
 
 gen_pdf() {
-    run_showing $compiler -interaction=nonstopmode \
-                -synctex=1 --halt-on-error "$@"
+    run_showing "$compiler" -interaction=nonstopmode -synctex=1 "$@"
 }
 
 gen_bib() {
@@ -108,6 +110,15 @@ bibtex_needed() {
         echo "$1" | grep -iq 'Please (re)run BibTeX on the file'
 }
 
+highlight_lines() {
+    if [ "$ascii" ]; then
+        cat
+    else
+        env GREP_COLORS='ms=00;36' \
+            grep -E 'l\.[0-9]+|line [0-9]+|$' --color=always
+    fi
+}
+
 build() {
     f="$1"
 
@@ -146,15 +157,15 @@ build() {
     fi
 
     ERRS=$(echo "$OUT" |
-               grep -A 1 -E '^\\! .+')
+               grep -A 1 -E '^! .+' | highlight_lines)
     WRNS=$(echo "$OUT" |
                grep -A 1 -E 'Warning:' |
-               grep -E '^[A-Za-z\(]')
+               grep -E '^[A-Za-z\(]' | highlight_lines)
 
-    if [ "$BIBOUT" ]; then
-        printf "$BLUE>>> BIBLIOGRAPHY:$RESET\n"
-        echo "$BIBOUT"
-    fi
+    # if [ "$BIBOUT" ]; then
+    #     printf "$BLUE>>> BIBLIOGRAPHY:$RESET\n"
+    #     echo "$BIBOUT"
+    # fi
     if [ "$ERRS" ]; then
         printf "$RED>>> ERRORS:$RESET\n"
         echo "$ERRS"
@@ -166,6 +177,11 @@ build() {
 
     garbage_hide "$f"
 
+    pdf="$f.pdf"
+    if [ ! -f "$pdf" ]; then
+        printf "$RED>>> FAILED:$RESET no PDF generated\n"
+        return 1
+    fi
     if [ "$ERRS" ]; then
         return 1
     fi
@@ -197,6 +213,59 @@ symbols() {
     column -s '|' -o '|' -t -H 1,5 <"$s" | less
 }
 
+find_tex_file() {
+    # first .tex file that begins a document
+    find . -maxdepth 1 -name '*.tex' | while read -r f; do
+        grep -q '\\begin{document}' "$f" && {
+            echo "$f"
+            return
+        }
+    done
+}
+
+jail() {
+    zip="$1"
+    [ -f "$zip" ] || {
+        echo No file found
+        return 1
+    }
+    zip=$(realpath "$zip")
+
+    jail_dir=$(mktemp -d)
+    mkdir -p "$jail_dir/doc/"
+    (
+        cp "$SELF" "$jail_dir/" &&
+            cd "$jail_dir/doc/" &&
+            unzip "$zip"
+    )
+
+    run_showing                    \
+        bwrap                      \
+        --bind / /                 \
+        --dev /dev                 \
+        --unshare-all              \
+        --die-with-parent          \
+        --bind "$jail_dir" "$HOME" \
+        /bin/sh -c                 \
+        'cd ~/doc/ && sh ~/latexwrapper 2>&1 | tee ~/log'
+
+    s=0
+    tex=$(cd "$jail_dir/doc/" && find_tex_file)
+    pdf="$jail_dir/doc/${tex%.*}.pdf"
+    if [ -f "$pdf" ]; then
+        target=$(dirname "$zip")
+        name=$(basename "$zip")
+        name="${name%.*}"
+        run_showing cp "$jail_dir/doc/${tex%.*}.pdf" "$target/${name}.pdf"
+        run_showing cp "$jail_dir/log" "$target/${name}.log"
+    else
+        s=1
+    fi
+
+    run_showing rm -r "$jail_dir"
+    return $s
+}
+
 show_help() {
     self=$(basename "$0")
     printf 'usage: %s [OPTION]... <CMD> <TEX_FILE>\n' "$self"
@@ -206,7 +275,7 @@ show_help() {
     echo '  -c, --compiler CC  latex compiler'
     echo
     echo 'Commands:'
-    echo '  b, build     compiler .tex document (default command)'
+    echo '  b, build     compile .tex document (default command)'
     echo '  c, clean     clean build files'
     echo '  s, symbols   tex symbol cheatsheet'
     echo '  t, template  generate a template .tex file'
@@ -227,6 +296,7 @@ main() {
             symbols|s)            cmd=symbols;   shift ;;
             template|t)           cmd=template;  shift ;;
             *.tex)                f="$a";        shift ;;
+            *.zip)                fz="$a";       shift ;;
 
             -h|--help)
                 show_help
@@ -247,8 +317,11 @@ main() {
         RESET=
     fi
 
-    if [ -z "$f" ]; then
-        f=$(find . -maxdepth 1 -name '*.tex' | head -n1)
+    if [ -f "$fz" ]; then
+        jail "$fz"
+        return
+    elif [ -z "$f" ]; then
+        f=$(find_tex_file)
     fi
     if [ ! -f "$f" ]; then
         case "$cmd" in
@@ -258,6 +331,7 @@ main() {
         esac
     fi
     f="${f%.*}"
+    # TODO: watch multiple bib files
     f_bib=$(find . -maxdepth 1 -name '*.bib' | head -n1)
 
     case "$cmd" in
