drawio, multi bib, cleanups

diff --git a/latexwrapper b/latexwrapper
--- a/latexwrapper
+++ b/latexwrapper
@@ -4,13 +4,14 @@ BLUE='\033[1;34m'
 RED='\033[1;31m'
 YELLOW='\033[1;33m'
 GREEN='\033[1;32m'
+CYAN='\033[1;36m'
 RESET='\033[0m'
 
 SELF=$(realpath "$0")
 
 f=
 fz=
-f_bib=
+f_bibs=
 f_dir=
 cmd=build
 compiler=pdflatex
@@ -21,7 +22,23 @@ run_showing() {
     "$@"
 }
 
+exists() {
+    command -v "$1" >/dev/null
+}
+
+info() {
+    printf "${BLUE}INFO:${RESET} %s\n" "$@"
+}
+
+err() {
+    printf "${RED}ERROR:${RESET} %s\n" "$@" >&2
+}
+
 gen_pdf() {
+    if ! exists "$compiler"; then
+        err "Failed compiling, $compiler is not installed. Exiting!"
+        exit 1
+    fi
     run_showing "$compiler" -interaction=nonstopmode -synctex=1 "$@"
 }
 
@@ -31,21 +48,52 @@ gen_bib() {
     else
         bibtexer=bibtex
     fi
+    if ! exists "$bibtexer"; then
+        err "Failed generating bibliography, $bibtexer is not installed. Skipping..."
+        return 1
+    fi
     run_showing "$bibtexer" "$@"
 }
 
 embed_fonts() {
+    if ! exists gs; then
+        err "Failed embedding fonts, gs is not installed. Skipping..."
+        return 1
+    fi
+    info 'Embedding fonts...'
     run_showing gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile="$1.embedded.pdf" "$1"
     run_showing mv "$1.embedded.pdf" "$1"
 }
 
-cleanup() {
-    printf "$RED>>> DELETING:$RESET\n"
-    n=$(basename "$f")
-    run_showing rm -rf "$f_dir/.$n.build"
-    if [ "$1" = '--pdf' ]; then
-        run_showing rm -f "$f_dir/$n.pdf" "$f_dir/$n.synctex.gz"
+build_drawio() {
+    dios=$(find -L . -type f -name '*.drawio' | while read -r dio; do
+               pdf=$(echo "$dio" | sed -r 's/\.drawio$/.pdf/')
+               if [ ! -f "$pdf" ] || newer_than "$dio" "$pdf"; then
+                   echo "$dio"
+               fi
+           done)
+
+    [ -n "$dios" ] || return 0
+
+    if ! exists drawio; then
+        err "Failed exporting drawio files, drawio is not installed. Skipping..."
+        return 1
     fi
+    info 'Exporting drawio files...'
+    echo "$dios" | run_showing xargs -l1 drawio --export -f pdf --crop
+    echo
+}
+
+cleanup() {
+    info 'Deleting build files...'
+    (
+        cd "$f_dir" || return 1
+        n=$(basename "$f")
+        run_showing rm -rf ".$n.build"
+        if [ "$1" = '--pdf' ]; then
+            run_showing rm -f "$n.pdf" "$n.synctex.gz"
+        fi
+    )
 }
 
 links() {
@@ -67,6 +115,18 @@ newer_than() {
         res=$(find "$1" -prune -newer "$2")
         [ -n "$res" ]
     }
+}
+
+any_newer_than() {
+    # returns 0 if any file in $1 is newer than $2
+    as="$1" # lines of file names
+    b="$2"
+    echo "$as" | while read -r target; do
+        if newer_than "$target" "$b"; then
+            return 1
+        fi
+    done || return 0
+    return 1
 }
 
 rerun_needed() {
@@ -91,6 +151,15 @@ highlight_lines() {
     fi
 }
 
+highlight_errs() {
+    if [ "$ascii" ]; then
+        cat
+    else
+        env GREP_COLORS='ms=00;31' \
+            grep -iE 'error|warning|$' --color=always
+    fi
+}
+
 build() {
     f="$1"
     links
@@ -98,6 +167,7 @@ build() {
     b="./.$n.build"
 
     (cd "$b" && build_real) && {
+        info 'Copying generated document...'
         for ext in pdf synctex.gz; do
             [ -f "$b/$n.$ext" ] &&
                 run_showing cp "$b/$n.$ext" "$n.$ext"
@@ -106,11 +176,18 @@ build() {
 }
 
 build_real() {
+    time_start=$(date "+%s")
+
+    # make sure all drawio files are compiled
+    build_drawio
+
+    info 'Building...'
+
     # first latex run
     if OUT=$(gen_pdf "$f.tex"); then
 
         # run bib if needed
-        if rerun_needed "$OUT" || newer_than "$f_bib" "$f.blg"; then
+        if rerun_needed "$OUT" || any_newer_than "$f_bibs" "$f.blg"; then
             if BIBOUT=$(gen_bib "$f") &&
                     ! echo "$BIBOUT" | grep -q 'does not contain any citations!'
             then
@@ -135,31 +212,44 @@ build_real() {
             [ "$reruns_ctr" = "$reruns_max" ] && break
         done
 
+        echo
         embed_fonts "$f.pdf"
     fi
 
+    echo
+    time_end=$(date "+%s")
+    time_diff=$((time_end - time_start))
+    info "Done, took ${time_diff} seconds"
+
     ERRS=$(echo "$OUT" |
-               grep -A 1 -E '^! .+' | highlight_lines)
+               grep -A 1 -E '^! .+' | highlight_errs | highlight_lines)
     WRNS=$(echo "$OUT" |
                grep -A 1 -E 'Warning:' |
-               grep -E '^[A-Za-z\(]' | highlight_lines)
+               grep -E '^[A-Za-z\(]' | highlight_errs | highlight_lines)
+    BIBOUT=$(echo "$BIBOUT" | highlight_errs | highlight_lines)
+    echo "$BIBOUT" | grep -iEq 'error|warning' || BIBOUT=
 
-    # if [ "$BIBOUT" ]; then
-    #     printf "$BLUE>>> BIBLIOGRAPHY:$RESET\n"
-    #     echo "$BIBOUT"
-    # fi
-    if [ "$ERRS" ]; then
-        printf "$RED>>> ERRORS:$RESET\n"
-        echo "$ERRS"
-    fi
-    if [ "$WRNS" ]; then
-        printf "$YELLOW>>> WARNINGS:$RESET\n"
-        echo "$WRNS"
-    fi
+    # shellcheck disable=SC2059
+    {
+        if [ "$ERRS" ]; then
+            printf "${RED}>>> ERRORS:${RESET}\n"
+            echo "$ERRS"
+        fi
+        if [ "$WRNS" ]; then
+            printf "${YELLOW}>>> WARNINGS:${RESET}\n"
+            echo "$WRNS"
+        fi
+        if [ "$BIBOUT" ]; then
+            printf "${CYAN}>>> BIBLIOGRAPHY:${RESET}\n"
+            echo "$BIBOUT"
+        fi
+    }
+
+    echo
 
     pdf="$f.pdf"
     if [ ! -f "$pdf" ]; then
-        printf "$RED>>> FAILED:$RESET no PDF generated\n"
+        err "No PDF generated"
         return 1
     fi
     if [ "$ERRS" ]; then
@@ -206,7 +296,7 @@ find_tex_file() {
 jail() {
     zip="$1"
     [ -f "$zip" ] || {
-        echo No file found
+        err 'No file found'
         return 1
     }
     zip=$(realpath "$zip")
@@ -257,7 +347,7 @@ jail() {
                  "$SELF" 2>&1 | tee ../log) ;;
 
         *)
-            echo "UNKNOWN jail method!"
+            err "UNKNOWN jail method!"
             return 1
     esac
 
@@ -317,7 +407,7 @@ main() {
                 return ;;
 
             *)
-                printf "Unknown argument '%s'" "$a"
+                err "Unknown argument '$a'"
                 show_help
                 return 1 ;;
         esac
@@ -340,14 +430,13 @@ main() {
     if [ ! -f "$f" ]; then
         case "$cmd" in
             build|clean)
-                printf "$RED>>> ERROR:$RESET '%s' is not a file\n" "$f"
+                err "'$f' is not a file"
                 return 1 ;;
         esac
     fi
     f_dir=$(dirname "$(realpath "$f")")
     f="${f%.*}"
-    # TODO: watch multiple bib files
-    f_bib=$(find . -maxdepth 1 -name '*.bib' | head -n1)
+    f_bibs=$(find . -maxdepth 1 -name '*.bib')
 
     case "$cmd" in
         build)    build         "$f" ;;
